# Generated by Django 4.0.4 on 2022-06-10 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=16)),
                ('cell_no', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=32)),
                ('admin', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('reference', models.URLField()),
                ('comment', models.TextField()),
                ('comment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Log_Record',
            fields=[
                ('location', models.CharField(max_length=16)),
                ('device', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=16)),
                ('time', models.DateTimeField()),
                ('login_no', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('link', models.URLField()),
                ('provider', models.CharField(max_length=16)),
                ('recipient', models.CharField(max_length=16)),
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('distributor', models.CharField(max_length=16)),
                ('provider', models.CharField(max_length=16)),
                ('purchase_time', models.DateTimeField()),
                ('purchase_details', models.TextField()),
                ('purchase_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
