# Generated by Django 4.0.4 on 2022-06-26 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abuse_reports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('violation', models.SmallIntegerField(choices=[('Spam', 'Spam'), ('Copyright Violation', 'Copyright Violation'), ('Flagged Content', 'Flagged Content')], default=0)),
                ('by_user', models.BooleanField()),
                ('by_system', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Bug_reports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('category', models.SmallIntegerField(choices=[('Data Loss', 'Data Loss'), ('Profile Registration', 'Profile Registration'), ('Messaging', 'Messaging')], default=0)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='To_do_list',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=64)),
                ('deadline', models.DateField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='level',
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.SmallIntegerField(choices=[('System Admin', 'System Admin'), ('Management Team', 'Management Team'), ('Site Admin', 'Site Admin')], default=0),
        ),
    ]
